<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/ws"
           elementFormDefault="qualified">

    <!--
        messageRequest
            name: string

        messageResponse:
            message: string
    -->
    <xs:element name="messageRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" type="xs:string" name="name"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="messageResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="message"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>