<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://example.com/ws"
           targetNamespace="http://example.com/ws"
           elementFormDefault="qualified">

    <xs:element name="messageResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message" type="tns:message"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="messageRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="name" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="message">
        <xs:sequence>
            <xs:element name="when" type="xs:dateTime"/>
            <xs:element name="message" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
