spring.application.name=ws
logging.level.org.springframework.web=debug
logging.level.org.springframework.ws=debug
#spring.webservices.wsdl-locations=classpath:/countries.xsd
spring.webservices.path=/ws