spring.application.name=ws
spring.webservices.wsdl-locations=classpath:/service.xsd
spring.webservices.path=/ws
logging.level.org.springframework.web=debug
logging.level.org.apache.wss4j=debug
logging.level.org.springframework.security=debug
logging.level.org.springframework.ws=debug
