spring.application.name=ws
spring.webservices.wsdl-locations=classpath:/service.xsd,classpath:/tokens.xsd
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090
spring.webservices.path=/ws
logging.level.org.springframework.web=trace
logging.level.org.apache.wss4j=trace
logging.level.org.springframework.security=trace
logging.level.org.springframework.ws=trace

spring.threads.virtual.enabled=true