spring.application.name=ws
spring.webservices.path=/ws
spring.webservices.wsdl-locations=classpath:/service.xsd
spring.threads.virtual.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090